from django.utils.translation import ugettext_lazy as _


MEDIA_OBJECT_MUSIC = 1
MEDIA_OBJECT_FILM = 2
MEDIA_OBJECT_TELEVISION = 3
MEDIA_OBJECT_TORRENT = 4
MEDIA_OBJECT_OTHER = 255
MEDIA_OBJECT_TYPE_CHOICES = (
    (MEDIA_OBJECT_MUSIC, _(u'music')),
    (MEDIA_OBJECT_FILM, _(u'film')),
    (MEDIA_OBJECT_TELEVISION, _(u'television')),
    (MEDIA_OBJECT_TORRENT, _(u'torrent')),

    (MEDIA_OBJECT_OTHER, _(u'other')),
)

ARTWORK_TYPE_OTHER = 255
ARTWORK_TYPE_CHOICES = (
    (ARTWORK_TYPE_OTHER, _(u'other')),
)

DEVICE_TYPE_INTEGRATED_AMPLIFIER = 1
DEVICE_TYPE_POWER_AMPLIFIER = 2
DEVICE_TYPE_OPERATIONAL_AMPLIFIER = 3
DEVICE_TYPE_TUBE_AMPLIFIER = 4
DEVICE_TYPE_PREAMPLIFIER = 5
DEVICE_TYPE_CARTRIDGE = 7
DEVICE_TYPE_TURNTABLE = 8
DEVICE_TYPE_OPTICAL_DISC_PLAYER = 9
DEVICE_TYPE_AUDIO_INTERFACE = 10
DEVICE_TYPE_CHOICES = (
    (DEVICE_TYPE_INTEGRATED_AMPLIFIER,_(u'Integrated amplifier')),
    (DEVICE_TYPE_POWER_AMPLIFIER,_(u'Power amplifier')),
    (DEVICE_TYPE_OPERATIONAL_AMPLIFIER,_(u'Operational amplifier')),
    (DEVICE_TYPE_TUBE_AMPLIFIER,_(u'Vacuum tube amplifier')),
    (DEVICE_TYPE_PREAMPLIFIER,_(u'Preamplifier')),
    (DEVICE_TYPE_CARTRIDGE,_(u'Cartridge (turntable)')),
    (DEVICE_TYPE_TURNTABLE,_(u'Turntable')),
    (DEVICE_TYPE_OPTICAL_DISC_PLAYER,_(u'Optical disc player')),
    (DEVICE_TYPE_AUDIO_INTERFACE,_(u'Audio interface')),
)

ENCODING_TYPE_MP3 = 'mp3'
ENCODING_TYPE_MP4 = 'mp4'
ENCODING_TYPE_OGG = 'ogg'
ENCODING_TYPE_FLAC = 'flac'
ENCODING_TYPE_DTS = 'dts'
ENCODING_TYPE_APE = 'ape'
ENCODING_TYPE_WV = 'wv'
ENCODING_TYPE_MPC = 'mpc'
ENCODING_TYPE_CHOICES = (
    (ENCODING_TYPE_MP3, _(u'MP3')),
    (ENCODING_TYPE_MP4, _(u'AAC')),
    (ENCODING_TYPE_OGG, _(u'OGG')),
    (ENCODING_TYPE_FLAC, _(u'FLAC')),
    (ENCODING_TYPE_DTS, _(u'DTS')),
    (ENCODING_TYPE_APE, _(u'APE')),
    (ENCODING_TYPE_WV, _(u'WavPack')),
    (ENCODING_TYPE_MPC, _(u'Musepack')),
)

BITRATE_192 = 1
BITRATE_APS = 2
BITRATE_V2 = 3
BITRATE_V1 = 4
BITRATE_256 = 5
BITRATE_APX = 6
BITRATE_V0 = 7
BITRATE_Q8_X = 8
BITRATE_320 = 9
BITRATE_LOSSLESS = 10
BITRATE_CHOICES = (
    (BITRATE_192,_(u'192bps')),
    (BITRATE_APS,_(u'APS (VBR)')),
    (BITRATE_V2,_(u'V2 (VBR)')),
    (BITRATE_V1,_(u'V1 (VBR)')),
    (BITRATE_256,_(u'256bps')),
    (BITRATE_APX,_(u'APX (VBR)')),
    (BITRATE_V0,_(u'V0 (VBR)')),
    (BITRATE_Q8_X,_(u'q8.x (VBR)')),
    (BITRATE_320,_(u'320bps')),
    (BITRATE_LOSSLESS,_(u'Lossless')),
)

BIT_DEPTH_16_BIT = 1
BIT_DEPTH_24_BIT = 2
BIT_DEPTH_32_BIT = 3
BIT_DEPTH_CHOICES = (
    (BIT_DEPTH_16_BIT, _(u'16bit')),
    (BIT_DEPTH_24_BIT, _(u'24bit')),
    (BIT_DEPTH_32_BIT, _(u'32bit')),
)

SAMPLING_FREQUENCY_44100 = 1
SAMPLING_FREQUENCY_48000 = 2
SAMPLING_FREQUENCY_88200 = 3
SAMPLING_FREQUENCY_96000 = 4
SAMPLING_FREQUENCY_176400 = 5
SAMPLING_FREQUENCY_192000 = 6
SAMPLING_FREQUENCY_CHOICES = (
    (SAMPLING_FREQUENCY_44100,_(u'44.1kHz')),
    (SAMPLING_FREQUENCY_48000,_(u'48kHz')),
    (SAMPLING_FREQUENCY_88200,_(u'88.2kHz')),
    (SAMPLING_FREQUENCY_96000,_(u'96kHz')),
    (SAMPLING_FREQUENCY_176400,_(u'176.4kHz')),
    (SAMPLING_FREQUENCY_192000,_(u'192kHz')),
)
